project:
  type: website
  output-dir: docs

website:
  title: "Probably Reliable"
  favicon: _images/general/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jelsema.github.io/ppcb/
        text: PPCB

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    toggle: true
    toc: true
    page-layout: full
    # css: styles.css
    # other themes: Spacelab

editor: source


