project:
  type: website
  output-dir: docs

website:
  title: "Probably Reliable"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jelsema.github.io/ppcb/
        text: PPCB

format:
  html:
    theme: 
      light: Spacelab  # Cerulean, Cosmo, Lumen, 
      dark: [Spacelab, theme-dark.scss]
    toggle: true
    preferred: light
    toc: true
    # css: styles.css

editor: source

