project:
  type: website
  output-dir: docs

website:
  title: "Probably Reliable"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jelsema.github.io/ppcb/
        text: PPCB

format:
  html:
    theme: Spacelab  # Cerulean, Cosmo, Lumen, 
    # css: styles.css
    toc: true

editor: source

