project:
  type: website
  output-dir: docs

website:
  title: "Probably Reliable"
  favicon: images/general/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jelsema.github.io/ppcb/
        text: PPCB

format:
  html:
    theme: 
      dark: Spacelab-dark
      light: Spacelab
    toggle: true
    preferred: light
    toc: true
    page-layout: full
    css: styles.css

editor: source


